# 院系 C MySQL（请按本机修改）
db.url=jdbc:mysql://127.0.0.1:3306/college_c_edu?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
db.user=root
db.password=123456

# 服务端口
college.c.gui.port=9000
college.c.xml.port=9100
integration.server.port=9200
