-- 院系 C 教务库（MySQL）— 结构参考课件表 3-10 ~ 3-12
CREATE DATABASE IF NOT EXISTS college_c_edu DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE college_c_edu;

DROP TABLE IF EXISTS sc;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS account;

CREATE TABLE account (
  acc VARCHAR(12) NOT NULL PRIMARY KEY,
  passwd VARCHAR(12) NOT NULL,
  CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student (
  Sno VARCHAR(9) NOT NULL PRIMARY KEY,
  Snm VARCHAR(10) NOT NULL,
  Sex VARCHAR(1) NOT NULL,
  Sde VARCHAR(6) NOT NULL,
  Pwd CHAR(6) NOT NULL,
  CONSTRAINT chk_sex CHECK (Sex IN ('M','F'))
) ENGINE=InnoDB;

CREATE TABLE course (
  Cno VARCHAR(9) NOT NULL PRIMARY KEY,
  Cnm VARCHAR(20) NOT NULL,
  Ctm INT NOT NULL,
  Cpt INT NOT NULL,
  Tec VARCHAR(20) NOT NULL,
  Pla VARCHAR(18) NOT NULL,
  Share CHAR(1) NOT NULL DEFAULT '0',
  CONSTRAINT chk_share CHECK (Share IN ('0','1'))
) ENGINE=InnoDB;

CREATE TABLE sc (
  Sno VARCHAR(9) NOT NULL,
  Cno VARCHAR(9) NOT NULL,
  Grd INT NOT NULL DEFAULT 0,
  PRIMARY KEY (Sno, Cno),
  CONSTRAINT fk_sc_student FOREIGN KEY (Sno) REFERENCES student(Sno) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_sc_course FOREIGN KEY (Cno) REFERENCES course(Cno) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
